import Head from 'next/head'
import Carousel from './Component/Carousel'
import style from "../styles/SearchBar.module.css";
import Searchbar from './Component/SearchBar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Carousel />
      <Searchbar />
    </>
  )
}